version: "3"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    restart: unless-stopped
    volumes:
      - /dataA/experiments/tamil.subramanian/qdrant_storage:/qdrant/storage
    ports:
      - 6333:6333
      - 6334:6334

  embed_service:
    image: wildme/wbia:nightly
    command: --https --container-name embed_service --engine-fast-lane-workers 1 --engine-slow-lane-workers 1 --pie-v2 --pie --miew-id
    volumes:
      - /dataA/experiments/tamil.subramanian/data/embed_services:/data/db
      - /dataA/experiments/tamil.subramanian/data:/data/wess
      - /data/cache:/cache
      - /dataA/experiments/tamil.subramanian/docker/vconfig:/v_config  
    ports:
      - 6018:5000
      - 6444:6444
      - 6445:6445
      - 8887:8887
    environment:
      HOST_UID: "${HOST_UID}"
      HOST_USER: "${HOST_USER}"
      WBIA_SENTRY_DSN: "${WBIA_SENTRY_DSN}"
    restart: unless-stopped
    shm_size: '32g'
    depends_on:
      - qdrant  # Ensures Qdrant starts first
      - git_setup  # Ensures the Python service is ready before running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]

  git_setup:
    image: python:3.10
    container_name: wess_service
    volumes:
      - /dataA/experiments/tamil.subramanian/data:/data
    working_dir: /data/wess
    entrypoint: >
      sh -c "
      if [ ! -d /data/wess/.git ]; then
        git clone https://github.com/WildMeOrg/wildes.git /data/wess;
      else
        cd /data/wess && git pull origin main;
      fi
      pip install -r /data/wess/requirements.txt &&
      nohup python3.10 -m uvicorn main:app --host 0.0.0.0 --port 6444 --reload &
      "
    depends_on:
      - qdrant  # Qdrant starts before this service
