version: "3"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    restart: unless-stopped
    volumes:
      - /dataA/experiments/tamil.subramanian/qdrant_storage:/qdrant/storage
    ports:
      - 6333:6333
      - 6334:6334

  git_setup:
    image: alpine/git  # Lightweight Git container
    container_name: git_clone_service
    volumes:
      - /dataA/experiments/tamil.subramanian/data:/data
    working_dir: /data
    entrypoint: >
      sh -c "
      if [ ! -d /data/wess/.git ]; then
        git clone https://github.com/WildMeOrg/wildes.git /data/wess;
      else
        cd /data/wess && git pull origin main;
      fi
      "

  embed_service:
    image: python:3.10
    container_name: wess_service
    env_file:
      - .env  # Loads environment variables
    volumes:
      - /dataA/experiments/tamil.subramanian/data:/data
    working_dir: /data/wess
    entrypoint: >
      sh -c "
      export QDRANT_HOST=${QDRANT_HOST}
      export QDRANT_PORT=${QDRANT_PORT}
      export API_KEY=${API_KEY}
      pip install -r /data/wess/requirements.txt &&
      nohup python3.10 -m uvicorn main:app --host 0.0.0.0 --port 6444 --reload &
      "
    depends_on:
      - qdrant
      - git_setup
    ports:
      - 6018:5000
      - 6444:6444
      - 6445:6445
      - 8887:8887
    restart: unless-stopped
